name: CI/CD Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:

  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          check_name: JUnit Test Report (${{ matrix.os }})
          report_paths: '**/build/test-results/test/TEST-*.xml'
